CREATE TABLESPACE SeleniumTest15x datafile 'SeleniumTest15x.dbf' SIZE 100M AUTOEXTEND ON NEXT  1M EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE USER TestUser IDENTIFIED BY TestUser Default TableSpace SeleniumTest15x Temporary TableSpace temp QUOTA UNLIMITED ON SeleniumTest15x;


alter USER TestUser IDENTIFIED BY TestUser Default TableSpace SeleniumTest15x Temporary TableSpace temp QUOTA UNLIMITED ON SeleniumTest15x;

grant EXP_FULL_DATABASE, IMP_FULL_DATABASE, CONNECT, RESOURCE , DBA to TestUser;
commit;



CREATE TABLE "TESTCASE" 
   (	
   	"SUITEID" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"SUITENAME" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"TESTCASENAME" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"STATUS" NUMBER NOT NULL ENABLE, 
	"STARTTIME" VARCHAR2(1000 BYTE), 
	"ENDTIME" VARCHAR2(1000 BYTE), 
	"ERRORMESSAGE" CLOB, 
	"XMLFILEPATH" VARCHAR2(4000 BYTE), 
	"CSVFILEPATH" VARCHAR2(4000 BYTE), 
	"EXECUTION_TIME" VARCHAR2(1000 BYTE), 
	"TESTCASEID" VARCHAR2(1000 BYTE),
	"ID" VARCHAR2(2000 BYTE),
	"VIDEO" VARCHAR2(4000 BYTE),
	"IMAGE" VARCHAR2(4000 BYTE)
   );
  
CREATE TABLE MASTERSUITE 
(
  "SUITEID" VARCHAR2(1000 BYTE) NOT NULL 
, "SUITENAME" VARCHAR2(1000 BYTE) NOT NULL 
, "STATUS" NUMBER NOT NULL 
, "STARTTIME" VARCHAR2(1000 BYTE) 
, "ENDTIME" VARCHAR2(1000 BYTE) 
, "EXECUTION_TIME" VARCHAR2(20 BYTE)
, "ID" VARCHAR2(2000 BYTE)
) ;
  

create table DataRegistration (
    suiteid     varchar2(1000) not null,
    regKey  varchar2(1000) not null,
    regValue  varchar2(4000) not null  
  );    
  
  commit;
    